# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1053de00220e76987061797a40153d309aa25daa53027380a29c15363fd381a8f35630cd927146e39f91604a0346a484d2aa988bff2fdc2fe798c1ef1a3e5820

test:
  secret_key_base: 9980dc1c24f6c39da519c9c10743cdd8739991d19eb9f6a7f75179a0a0dcdf162ce6a73e3511b068d394a3adc5bdb65c2b38863d9b4f401c28ce360497d2cd74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
